### PR TITLE
Define Color Scheme

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
This should make for a consistent experience
across terminals. This defines a basic black/white
color scheme.

 #Hacktoberfest

Each terminal defines its concepts of **Black** and **White**.

## In iTerm2

image

## Inside JetBrains Rider (Dark Theme)

Screenshot 2020-09-24 at 15 33 21@2x

### CODE REVIEW

**Comment by mholo65** [comment]
Thanks! I'm going to play with this a little on Windows as well before merging.

**Comment by khalidabuhakmeh** [comment]
Found an issue with JetBrains Rider not capture the `Shift+Tab` keystroke. It seems to work fine in `iTerm2`.

**Comment by mholo65** [comment]
Fixes #9

**Comment by mholo65** [comment]
Thanks @khalidabuhakmeh! I inverted the color scheme as the other one felt too bright in Windows Terminal.

**Pull request merged**
